### ISSUE TITLE
Only one of multiple claims that are in the way of creating a new claim is shown

### ISSUE THREAD

**Issue by aljaxus** [bloodmc/GriefDefender#17]
Server version: 1.12.2
Plugin version: 1.0.2-RC2

Issue:
When trying to create a new claim that overlaps other claims, only one claim that is in the way is shown

- all claims in the area [image](https://share.aljaxus.eu/2019-07-28/04%3A47%3A05pm-2019-07-28_17.45.59.png)

1. start creating a new claim [image](https://share.aljaxus.eu/2019-07-28/04%3A47%3A05pm-2019-07-28_17.46.25.png)
2. attempt create one that overlaps other claims
3. Only one of the claims will be shown [image](https://share.aljaxus.eu/2019-07-28/04%3A47%3A04pm-2019-07-28_17.46.30.png)

// edit1 - added plugin version

**Comment by bloodmc** [comment]
So the reason only the clicked claim is shown is for performance reasons. If you have many players attempting to claim large areas then it adds up since GD would have to gather all claims within each selected area. By showing only the claim clicked, the server is able to save resources.

However, in 1.1.0 each claim you click will stay visualized until you complete your creation.

**Comment by aljaxus** [comment]
It does not show only the claim "clicked", because I clicked outside of the shown claim.
It might show only one claim, but not "the clicked claim" because there is none.

**Comment by bloodmc** [comment]
It does in GD 1.1.0

**Comment by aljaxus** [comment]
> Actually, I meant to say it will ONLY show the first overlap claim it finds if there was none at the clicked spot. There will be no support for ALL overlapped claims as that would just waste performance.

Understandable.
