### ISSUE TITLE
[Feature request] Additional context group for #signs

### ISSUE THREAD

**Issue by RobinWhitfield** [bloodmc/GriefDefender#202]
Signs are often used by plugins to perform functions and although they tend to work, GriefDefender throws a "you don't have permission" message in chat.

Adding interact-block-primary and interact-block-secondary for all types of sign works, but it's quite a long list so not ideal.

Would it be possible to have a context group for this? Maybe also one for #containers?

**Comment by DrWurzeli** [comment]
Request is for new Context Group Keys.

I will add some examples from the [SpigotAPI](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html) for bukkit - might be different for sponge.

#sign
ACACIA_SIGN
BIRCH_SIGN
DARK_OAK_SIGN
JUNGLE_SIGN
OAK_SIGN
SPRUCE_SIGN
ACACIA_WALL_SIGN
BIRCH_WALL_SIGN
DARK_OAK_WALL_SIGN
JUNGLE_WALL_SIGN
OAK_WALL_SIGN
SPRUCE_WALL_SIGN

#bed
BLACK_BED
BLUE_BED
BROWN_BED
CYAN_BED
GRAY_BED
GREEN_BED
LIGHT_BLUE_BED
LIGHT_GRAY_BED
LIME_BED
MAGENTA_BED
ORANGE_BED
PINK_BED
PURPLE_BED
RED_BED
WHITE_BED
YELLOW_BED

#shulkerbox
shulker_box
white_shulker_box
orange_shulker_box
magenta_shulker_box
light_blue_shulker_box
yellow_shulker_box
lime_shulker_box
pink_shulker_box
gray_shulker_box
light_gray_shulker_box
cyan_shulker_box
purple_shulker_box
blue_shulker_box
brown_shulker_box
green_shulker_box
red_shulker_box
black_shulker_box

maybe - since container trust is already a thing and might confuse people.
#container
CHEST
CHEST_MINECART
ENDER_CHEST
TRAPPED_CHEST
BARREL

**Comment by bloodmc** [comment]
Latest development builds for 1.14+ now have support for mojang's tag system.

See https://minecraft.gamepedia.com/Tag
