### ISSUE TITLE
interact-item-secondary returning true for some items

### ISSUE THREAD

**Issue by clienthax** [bloodmc/GriefDefender#268]
https://griefdefender.github.io/debug/?gJJQhYkDX7
https://griefdefender.github.io/debug/?4BNlap3Ja5

Sponge
GD: 1.5.0

![image](https://user-images.githubusercontent.com/1056270/91643525-da965500-ea2b-11ea-9721-7a3c8ac4b6a0.png)

**Comment by bloodmc** [comment]
The screenshot just shows GD's ChangeBlockEvent.Pre bypassing the listener which is fine. GD will handle item interactions in its item listener. Since the debug links are long removed, I'm assuming this is a permission issue if it ended up showing true in gddebug. Please retest with latest GD Sponge and provide the proper information needed such as LP verbose, versions, gddebug etc..
