### ISSUE TITLE
[REQUEST] Protection to the target inside the claim

### ISSUE THREAD

**Issue by martin1194** [bloodmc/GriefDefender#331]
- **Feature information**

In this debug log, a player using a gun pointing at a block is inside the claim when the player standing in wildness. That block must be protect when that player no any permission. If add the feature to check the target location. I can make this to false
https://griefdefender.github.io/debug/?wfgLpy3m2a

- **Other plugins or mods related to the request**

botania

- **Additional context**

**Comment by DrWurzeli** [comment]
have you tried setting it to FALSE so it actually gets blocked?

**Comment by martin1194** [comment]
Of couse yes, but only the source inside the claim. It can be log as false. If the source outside the claim and try to wreck the claim. It will be wreck.

**Comment by bloodmc** [comment]
This has nothing to do with GD. GD relies on events to be fired. If no event is fired then there is nothing GD can do. I highly suggest you use SpongeForge if you are going to be using many mods on a server. Sponge added many features to properly support hundreds of mods over the years. Magma/Mohist literally relies on Forge events which many mods never even use properly. You will always run into many limitations with Mohist/Magma due to poor event support for mods.

**Comment by martin1194** [comment]
um. Can it find the source location? Or there are no any way to find source location?
